---
- hosts: localhost
  connection: local
  vars:
    user: mm
  tasks:
  - name: ansible-mm
    azure_rm_resourcegroup:
      name: "webserver_{{ user }}"
      location: northeurope
      tags:
          solution: "webserver_{{ user }}"
          delete: ansibletraining
    register: rg
  - debug:
      var: rg